#!/bin/bash
#
# Gaia Sandbox start script.
#

SOURCE="${BASH_SOURCE[0]}"
while [ -h "$SOURCE" ]; do # resolve $SOURCE until the file is no longer a symlink
  DIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
  SOURCE="$(readlink "$SOURCE")"
  [[ $SOURCE != /* ]] && SOURCE="$DIR/$SOURCE" # if $SOURCE was a relative symlink, we need to resolve it relative to the path where the symlink file was located
done


GSDIR="$( cd -P "$( dirname "$SOURCE" )" && pwd )"
LIB_PATH="$GSDIR/gaiasandbox.jar"

#
# Choose java - use JAVA_HOME, if set.
#
if [ "$JAVA_HOME" != "" ]; then
	JAVA="$JAVA_HOME/bin/java"
else
	JAVA="java"
fi

#
# Settings.
#
# Properties file
OPTS="$OPTS -Dproperties.file=$GSDIR/conf/global.properties"

# Memory
OPTS="$OPTS -Xmx512m"
# Parallel GC 
OPTS="$OPTS -XX:+UseParallelGC"
# GC debug only
#OPTS="$OPTS -verbose:gc -XX:+PrintGCDetails"
# JIT compiler debug only
#OPTS="$OPTS -XX:+PrintCompilation"
# Even more JIT compiler debugging - This produces a huge XML log file (for JITWatch)
#OPTS="$OPTS -XX:+UnlockDiagnosticVMOptions -XX:+TraceClassLoading -XX:+LogCompilation -XX:+PrintAssembly"

#
# Run.
#

OLDDIR="$( pwd )"

cd $GSDIR
CMD="$JAVA $OPTS -cp $LIB_PATH gaia.cu9.ari.gaiaorbit.desktop.GaiaSandboxDesktop $@"
echo "$CMD"
$CMD

cd $OLDDIR
